repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py314-plus]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=THIRDPARTY,hass,alot,datas,dof,dur,farenheit,hist,iff,ines,ist,lightsensor,mut,nd,pres,referer,ser,serie,te,technik,ue,uint,visability,wan,wanna,withing
          - --skip="./.*,*.csv,*.json,*.js"
          - --quiet-level=2
        exclude_types: [csv, json]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.15.21
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyclean
        name: pyclean
        entry: pyclean .
        language: system
        always_run: true
        pass_filenames: false
