name: Release Drafter

on:
  push:
    branches: [main]

# Permissions for default token
permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    if: github.actor != ${{ vars.RELEASE_BOT_COMMITTER_NAME }} # Prevent endless loops
    runs-on: ubuntu-latest
    steps:
      - name: Create release-bot token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.RELEASE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

      - uses: release-drafter/release-drafter@v7
        id: release-drafter
        with:
          config-name: release-drafter.yml
          token: ${{ steps.app-token.outputs.token }}

      # Update version number in pyproject.toml
      - uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Store tag version
        id: version
        run: |
          tag="${{ steps.release-drafter.outputs.tag_name }}"
          echo "version=${tag:1}" >> $GITHUB_OUTPUT

      - name: Update version in required files
        run: |
          sed -i "s/version = .*/version = \"${{ steps.version.outputs.version }}\"/g" pyproject.toml
          sed -i "s/release = .*/release = \"${{ steps.version.outputs.version }}\"/g" docs/source/conf.py
          sed -i "s/aio-remeha-modbus>=.*/aio-remeha-modbus>=${{ steps.version.outputs.version }}/g" README.md

      - name: Install uv and dependencies
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3

      - name: Synchronize uv.lock file
        run: uv sync

      - name: Commit version changes
        run: |
          if ! git diff --quiet; then
            git config user.name "${{ vars.RELEASE_BOT_COMMITTER_NAME }}"
            git config user.email "${{ vars.RELEASE_BOT_COMMITTER_EMAIL }}"
            git commit -am "Bump version to ${{ steps.version.outputs.version }}"
            git push
          fi
